#!/usr/bin/perl

my $lib_path=`echo $0 | sed "s/\$(basename $0)//g"`;
chomp($lib_path);
$lib_path =~ s/\/$//;
require("$lib_path/common");

my $lvs_tool = "$lib_path/bvsadm";
my $cmd = `basename $0`;
chomp($cmd);
my $param_str = $cmd;

my $i;
for ($i = 1; $i <= $#ARGV; $i++) {
    chomp($ARGV[$i]);
    $param_str .= " ".$ARGV[$i];
}

my ($status_code, $param) = get_cmd_param("$param_str");
my $lvs_path = get_value("$param_str", " lvs_path=");

chomp($status_code);


if ($status_code eq 0) {
    my $lvs_conf_cmd = "$lvs_tool $param";
    print "add_alarm: $lvs_conf_cmd\n";
    my $ret = `$lvs_conf_cmd`;
    if ($? ne 0) {
	print "lvs config failed: $lvs_conf_cmd, $ret\n";
        if ($ret =~ /already exist/) {
	    next;
        }
	exit 1;
    } else {
	print "Success\n";
    }
} else {
    write_msg($status_code);   
}

