#!/usr/bin/perl

my $lib_path=`echo $0 | sed "s/\$(basename $0)//g"`;
chomp($lib_path);
$lib_path =~ s/\/$//;
require("$lib_path/common");

my $lvs_tool = "$lib_path/bvsadm";
my $cmd = `basename $0`;
chomp($cmd);
my $param_str = $cmd;

my $i;
for ($i = 1; $i <= $#ARGV; $i++) {
    chomp($ARGV[$i]);
    $param_str .= " ".$ARGV[$i];
}

my ($status_code, $param) = get_cmd_param("$param_str");
my $lvs_path = get_value("$param_str", " lvs_path=");

chomp($status_code);


if ($status_code eq 0) {
    do_config("$lvs_tool $param", "$lvs_path");
    my $vip = get_value("$param_str", "vip=");
    my $cmd = "grep -r \"$vip\" $lvs_path | grep -v \"\\<svn\\-base\\>\" | grep -v \"\\<log\\>\\|lvscheck.ops.vnet\\|alarm_service\\|lvs_tempplate\" | awk -F ':' '{print \$1}' | head -n 1";
    my $res = `$cmd`;
    chomp $res;
    if ($res eq "") {
	chdir $lvs_path;
	print "$lvs_tool del_alarm vip=$vip\n";
	`$lvs_tool del_alarm vip=$vip`;
    }
} else {
    write_msg($status_code);   
}

