#!/usr/bin/perl

my $lib_path=`echo $0 | sed "s/\$(basename $0)//g"`;
chomp($lib_path);
$lib_path =~ s/\/$//;
require("$lib_path/common");

my $lvs_tool = "$lib_path/bvsadm";
my $cmd = `basename $0`;
chomp($cmd);
my $param_str = $cmd;

my $i;
for ($i = 1; $i <= $#ARGV; $i++) {
    chomp($ARGV[$i]);
    $param_str .= " ".$ARGV[$i];
}

my ($status_code, $param) = get_cmd_param("$param_str");
my $lvs_path = get_value("$param_str", " lvs_path=");
my $vip = get_value("$param_str", "vip=");
my $service_name = get_value("$param_str", "service_name=");
my $sms_alarm = get_value("$param_str", "sms_alarm=");
my $email_alarm = get_value("$param_str", "email_alarm=");

chomp($status_code);


if ($status_code eq 0 && $vip != "") {
    my @tmp = split(/ /, $param);
    my $sub_param = "";
    foreach my $i (1..$#tmp) {
	$sub_param .= " $tmp[$i] ";
    }

    my $del_alarm_cmd = "$lvs_tool del_alarm vip=$vip";
    my $add_alarm_cmd = "$lvs_tool add_alarm $sub_param";
    my $ret = `$del_alarm_cmd`;

    if ($? ne 0) {
	print "lvs config failed: $del_alarm_cmd, $ret\n";
	exit 1;
    }

    if ($service_name eq "" and $sms_alarm eq "" and $email_alarm eq "") {
	print "Success\n";
	exit 0;
    }     

    $ret = `$add_alarm_cmd`;
    if ($? ne 0) {
	print "lvs config failed: $add_alarm_cmd, $ret\n";
	exit 1;
    }

    print "Success\n";

} else {
    write_msg($status_code);   
}

