#!/usr/bin/perl

my $lib_path=`echo $0 | sed "s/\$(basename $0)//g"`;
chomp($lib_path);
$lib_path =~ s/\/$//;
require("$lib_path/common");

my $CURL_VIP_TOOL = "/home/lvs/online-conf/tools/lvsCheck.py";

my $lvs_tool = "$lib_path/bvsadm";
my $cmd = `basename $0`;
chomp($cmd);
my $param_str = $cmd;

my $i;
for ($i = 1; $i <= $#ARGV; $i++) {
    chomp($ARGV[$i]);
    $param_str .= " ".$ARGV[$i];
}
my ($status_code, $param) = get_rs_cmd_param("$param_str");
my $lvs_path = get_value("$param_str", " lvs_path=");
chomp($status_code);

if ($status_code eq 0) {
    opendir(TEMP, $lvs_path) || die "Cannot open $lvs_path:$!";
    my @FILES = readdir TEMP;
    for(my $index = 0; $index < @FILES; $index++) {
	if ($FILES[$index] =~ "qihoo.net") {
	    $lvs_cmd = "$CURL_VIP_TOOL -a -H $FILES[$index]";
	    print "cmd: $lvs_cmd\n";
	    my $res = system("$lvs_cmd &");
	    if ($? == 0) {
		print "Success\n";
	    } else {
		print "Failed\n";
	    }
	    last;

	}
    }
    closedir(TEMP);
} else {
    write_msg($status_code);   
}

