#!/usr/bin/perl
# $Description: Show
# $Date: 2010-03-22
# $Bug-Report: stl-net@baidu.com
# $ChangeLog:

use strict;
use warnings;
require("/home/bvs-manager/bvs/common.pl");

my %vs =
(
	'vip'=>'',
	'vport'=>'',
	'protocol'=>'TCP'
);

my $CAT_CMD="/bin/cat ";
my $proc_ip_vs_file = "/proc/net/ip_vs";
my @ip_vs_info_hex = ();
my @vs_rs_hex = ();
my $result = 1;

my %op_num_msg =
(
	'0'=>"Success",
	'102'=>"Invalid option",
	'221'=>"/proc/net/ip_vs doesn't exist",
	'222'=>"/proc/net/ip_vs read error",
	'231'=>"Can't find the virtual server"
);

###############
# Functions
###############
# Show usage
sub show_usage($)
{
	err_exit("Usage:\n$0	<VIP> <Vport> <Protocol> \n$0	<VIP> <Vport>", 0);
}

sub init_opt
{
	# Get vip and vport
	if (is_ip($ARGV[0]) and is_port($ARGV[1]))
	{
		my @tmp_ip_seg = split('\.', $ARGV[0]);
		foreach my $ip_seg (@tmp_ip_seg)
		{
			$vs{'vip'} .= oct_to_hex($ip_seg, 2);
		}
		
		$vs{'vport'} = oct_to_hex($ARGV[1], 4);
	}
	else
	{
		err_exit("$op_num_msg{'102'}", 102);
	}

	# Get protocol
	if (defined($ARGV[2]))
	{
		if(is_protocol($ARGV[2]))
		{
			$vs{'protocol'}=$ARGV[2];
		}
		else
		{
			err_exit("$op_num_msg{'102'}", 102);
		}
	}
}

sub list_vs_rs
{
	my $flag_in_vs = 0;
	my $ret = 231;
	if(not -f $proc_ip_vs_file)
	{
		err_exit("$op_num_msg{'221'}", 221);
	}
	@ip_vs_info_hex = `$CAT_CMD $proc_ip_vs_file`;
	if($? ne 0)
	{
		err_exit("$op_num_msg{'222'}", 222);
	}

	foreach my $line (@ip_vs_info_hex)
	{
		if($flag_in_vs eq 1)
		{
			if($line =~ /\s+\-\>\s+([0-9A-F]+):([0-9A-F]+)\s+(\w+)\s+(\d+)\s+(\d+)\s+(\d+)/)
			{
				my $oct_port = hex($2);
				my $oct_ip = hex_to_ip($1);
				print("$oct_ip:$oct_port	$3	$4	$5	$6\n");
			}
			else
			{
				last;
			}
		}
		if($line =~ /$vs{'protocol'}\s+$vs{'vip'}:$vs{'vport'}\s+\w+/)
		{
			$flag_in_vs = 1;
			$ret = 0;
			print("RealServerIP:Port	Forward	Weight	ActiveConn	InActConn\n");
		}
	}
	return $ret;
}

################
# Main process
################
if ($#ARGV ne 1 and $#ARGV ne 2)
{
	show_usage($0);
}

init_opt();
$result = list_vs_rs();
err_exit("$op_num_msg{$result}", $result);
