#!/usr/bin/perl
# $Description: Show virtual servers.
# $Date: 2010-03-26
# $Bug-Report: stl-net@baidu.com
# $ChangeLog:

use strict;
use warnings;
require("/home/bvs-manager/bvs/common.pl");

my $proc_ip_vs = "/proc/net/ip_vs";
my $CAT_CMD="/bin/cat ";
my @ip_vs_info;
my $i;
my %show_vs_num_msg =
(
	'102'=>"Invalid option",
	'221'=>"/proc/net/ip_vs doesn't exist",
	'222'=>"/proc/net/ip_vs read error",
);

if(not -f $proc_ip_vs)
{
	err_exit("$show_vs_num_msg{'221'}", 221);
}

@ip_vs_info = `$CAT_CMD $proc_ip_vs`;
if($? ne 0)
{
	err_exit("$show_vs_num_msg{'222'}", 222);
}

my $ip;
my $port;
for($i = 3; $i <= $#ip_vs_info; $i ++)
{
	if($ip_vs_info[$i] =~ /^(\w+)\s+([0-9A-F]+)\:([0-9A-F]+)/)
	{
		$ip = hex_to_ip($2);
		$port = hex($3);
		print("$1 $ip:$port\n")
	}
}
err_exit("Success", 0);
